version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=your_database
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb-volume:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

  api-service:
    build: ./api-flask
    volumes:
      - ./api-flask/:/usr/src/app/
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
    ports:
      - 5000:5000
volumes:
        mongodb-volume: {}
